name: Jesse Newland'
description: Send Open Sound Control messages in GitHub Actions workflows.
author: Urcomputeringpal
inputs:
  host:              
    description: host
    required: true
  port:              
    description: port
    required: true
  separator:              
    description: if present, message is split by this value
    required: false
  message:              
    description: the message to send
    required: true
  endpoint:              
    description: endpoint
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
